docs/other-topics/resources.md

This is a small PR that updates the 'Awesome Sequelize' resource.
I've merged all categories that included a single item together. I've also moved libraries that haven't been updated in a long time to the "Outdated" category.
I've added sequelize-pg-utilities, sequelize-test-helpers, and dataloader-sequelize

docs: update awesome sequelize

---

docusaurus.config.js
src/css/custom.scss

Add netlify reference to qualify for open source plan

---

docs/core-concepts/model-querying-basics.md
docs/core-concepts/validations-and-constraints.md
docs/intro.mdx
docs/other-topics/whos-using.md
versioned_docs/version-6.x.x/core-concepts/validations-and-constraints.md
versioned_docs/version-6.x.x/intro.md
versioned_docs/version-6.x.x/other-topics/other-data-types.md
versioned_docs/version-6.x.x/other-topics/resources.md

See https://github.com/sequelize/website/issues/61, but on top of it I've also updated mentions of HTTP and links.
Closes #61

feat: upgrade all http links to https

---

static/_redirects

Add redirect for v3 legacy docs

---

docs/other-topics/upgrade.md

See https://github.com/sequelize/sequelize/pull/14352

document breaking change from sequelize/14352

---

docusaurus.config.js

This PR makes the edit button at the end of documentation pages lead to the right file on our repository :)

Fix edit url

---

docs/getting-started.mdx
versioned_docs/version-6.x.x/getting-started.md

feat; document about reconnecting the closed database connection in Sequelize

---

.github/workflows/draft.yml
.github/workflows/main.yml
README.md

Mirroring the excellent PR https://github.com/sequelize/sequelize/pull/14473

Cancel concurrent builds on PRs

---

docs/other-topics/migrations.md

Remade from #102 and move it between creating first model and running a migration.

docs: reorder migration

---

renovate.json

It won't fix #149 but it will make recreating the lockfile easier.

build(renovate): unify config with main repo

---

versioned_docs/version-6.x.x/other-topics/naming-strategies.md

Fixed typo `referencced` to `referenced` on line 89

Fix typo : `referencced` to `referenced`

---

src/pages/releases.mdx

See https://github.com/sequelize/sequelize/pull/14587

docs(mssql): add support for MSSQL 2022

---

docs/other-topics/other-data-types.mdx

Found a minor mistake in the BLOBs documentation. This PR fixes it!

Minor fix to BLOBs documentation

---

versioned_docs/version-6.x.x/other-topics/resources.md

Hi, can I add this sample integration to resources?  it's a clever use case that could be helpful add to the page

Adding a sample(s) to resources?

---

docusaurus.config.js

This PR adds support for a search bar, courtesy of Algolia Docsearch :)
closes #57

feat: add algolia based search support

---

src/pages/releases.mdx

Relates to https://github.com/sequelize/sequelize/pull/15284

docs: update TS support

---

src/pages/releases.mdx

See https://github.com/sequelize/sequelize/pull/15289

meta: update minimal supported version of postgres

---

docs/other-topics/typescript.mdx
docs/other-topics/upgrade.md

meta: update minimal TS version

---

docs/other-topics/upgrade.md

See https://github.com/sequelize/sequelize/pull/15441

fix: Reflect updated Sequelize.AbstractQueryInterface

---

versioned_docs/version-6.x.x/advanced-association-concepts/advanced-many-to-many.md

Datatype of game was changed from INTEGER to STRING

Datatype of game name changed

---

docs/other-topics/upgrade.md

This PR documents the breaking changes introduced by https://github.com/sequelize/sequelize/pull/15598
I'll document the updated behaviors in https://github.com/sequelize/website/pull/330

feat: document breaking changes of https://github.com/sequelize/sequelize/pull/15598

---

docs/other-topics/upgrade.md

See https://github.com/sequelize/sequelize/pull/15879

docs: document deprecated quoteIdentifiers option

---

docs/other-topics/resources.md
versioned_docs/version-6.x.x/other-topics/resources.md

sequelizemm library added to resource page.

 sequelizemm library added to resource page.

---

package.json
src/utils/use-storage.tsx
yarn.lock

Replaces https://github.com/sequelize/website/pull/461

meta: update eslint config

---

src/pages/releases.mdx

See https://github.com/sequelize/sequelize/pull/16133

docs: update minimum mariadb version

---

docs/other-topics/resources.md
versioned_docs/version-6.x.x/other-topics/resources.md

Adding `@hatchifyjs/sequelize-create-with-associations` to the resource page

docs: Add sequelize-create-with-associations to resources

---

.github/workflows/draft.yml

meta: fix draft build link retrieval

---

docs/other-topics/upgrade.md

I believe this is a typo, as the sentence doesn't make sense the way it's currently written.

docs: fix typo in upgrade to v7 page

---

static/_redirects

meta: add redirects to v4/v5 upgrade guide

---

docs/other-topics/upgrade.md
docs/querying/json.mdx

This PR documents the feature introduced in PR https://github.com/sequelize/sequelize/pull/16861, see that PR for details

Document the option to control the behavior of null in JSON attributes

---

package.json
tsconfig.json
yarn.lock

See https://docusaurus.io/docs/migration/v3#typescript-base-config

meta: use internal docusaurus tsconfig

---

docs/models/getters-setters-virtuals.md
docs/other-topics/upgrade.md

Clarify date parsing behavior

---

docs/models/data-types.mdx

See https://github.com/sequelize/sequelize/pull/17059

Add MACADDR8 DataType

---

docs/other-topics/resources.md
versioned_docs/version-6.x.x/other-topics/resources.md

Corrected package spelling

---

docs/querying/select-methods.md

This PR documents PR https://github.com/sequelize/sequelize/pull/17393

document composite PK support in findByPk
