sequelize/website

docs/other-topics/legacy.md
versioned_docs/version-6.x.x/other-topics/legacy.md

Brings https://github.com/sequelize/sequelize/pull/14233#pullrequestreview-908129128 in the new documentation website. It documents that which instance methods should not (and, in the future, cannot) be used if the Model has no primary keys.

docs: document limitations of the no-pk approach

---

docs/other-topics/other-data-types.mdx
docs/other-topics/typescript.mdx

This PR brings the different documentation changes that have been merged in the main repo since the migration.
It:
- Documents the new `Range` type
- Documents the new `ForeignKey` type
- Removes the "untyped" version of `sequelize.define` from the typescript documentation, because the new way of typing models is just as easy as not typing, so there isn't a good reason to not type models anymore.

docs: bring docs changes from main repo

---

.github/workflows/main.yml

Currently (before this PR), we were having the following CI/CD flow
1. A change is merged to main
2. The build on main syncs code/builds the docs/uploads to gh-pages
3. Netlify observes all changes to gh-pages and essentially just takes whatever is in the root dir and uploads it to the CDN
After this PR
1. A change is merged to main
2. The build on main syncs code/builds the docs/uploads the build directory straight to Netlify.
Since the preview doesn't seem to work properly, we could tweak in a way that it will create draft versions for any code change outside of the main branch. What do you think?
This is what you'll see in netlify
This is how a build looks like https://github.com/sequelize/website/actions/runs/2079276392
PS: The reason why the draft doesn't work is very like because of …

Swap Github Pages based deployment with direct netlify deployments

---

docs/core-concepts/model-querying-basics.md
versioned_docs/version-6.x.x/core-concepts/model-querying-basics.md

Copied from https://github.com/sequelize/sequelize/pull/14123
The [tests mentioned there](https://github.com/sequelize/sequelize/blob/1d6336f32320c66b004f6089c4bc39195904e355/test/unit/sql/where.test.js#L608-L623) has been superseded, but it seems that https://github.com/sequelize/sequelize/blob/main/test/unit/sql/where.test.ts#L508-L510 is the replacement

docs(op): fix queries example for [Op.any]

---

docs/index.mdx
docs/other-topics/upgrade-to-v7.md

See https://github.com/sequelize/sequelize/pull/14339

feat: drop support for node 12

---

docs/other-topics/resources.md

Adds [sequel-ace-typescript-bundles](https://github.com/binlabs/sequel-ace-typescript-bundles) to the list of resources under the `Code generation & visualisers` heading.

docs: Add sequel-ace-typescript-bundles to Resources page

---

docs/core-concepts/model-querying-basics.md
docs/core-concepts/raw-queries.md
docs/other-topics/upgrade.md

This PR documents https://github.com/sequelize/sequelize/pull/14447
It also clarifies that `bind` & `replacements` can be used in `literal()`
It also changes a few uses of `sequelize.fn` and the like with `fn`. Doing that removes a lot of noise from queries, and removes the assumption that users need to pass their `sequelize` instance around to use these functions.

document changes in bind & replacements

---

docs/other-topics/dialect-specific-things.md
versioned_docs/version-6.x.x/other-topics/dialect-specific-things.md

As [mentioned in this issue](https://github.com/sequelize/sequelize/issues/12329#issuecomment-1126053235), Sequelize's documentation mentions `dialectOptions.readWriteMode`, but that option is actually named [`dialectOptions.mode`](https://github.com/sequelize/sequelize/blob/main/src/dialects/sqlite/connection-manager.js#L64).
Relevant pages:
- https://sequelize.org/docs/v6/other-topics/dialect-specific-things/#sqlite
- https://sequelize.org/docs/v7/other-topics/dialect-specific-things/#sqlite

docs: update sqlite's mode option docs

---

docs/other-topics/typescript.mdx

https://github.com/sequelize/sequelize/pull/14649 changed the casing of the files we reference in the documentation. This PR updates the relevant imports, so the website can build again.

fix: update links to typescript snippets

---

versioned_docs/version-6.x.x/other-topics/transactions.md

Added note about the origin of the `sequelize` object.
The origin of the line is ambiguous and not are clear if I need to use my connection or a `Sequelize` dependency
```javascript
const t = await sequelize.transaction();
```
You can check here more people with this confusion [https://stackoverflow.com/questions/62273766/typeerror-sequelize-transaction-is-not-a-function](https://stackoverflow.com/questions/62273766/typeerror-sequelize-transaction-is-not-a-function)

docs(v6): Update transactions.md

---

docs/other-topics/upgrade.md

As requested in PR https://github.com/sequelize/sequelize/pull/14903.

docs: add info on afterCommit hooks in upgrade guide

---

src/pages/releases.mdx

The release table was a bit broken because we were not escaping ||. We have also dropped TS 4.4 support for `main`

fix: escape | in releases table and update TS support

---

renovate.json

This aligns our renovate config with the main repo (with one difference: it auto-merges lockfile maintenance PRs).

meta: auto-merge renovate PRs

---

renovate.json

We need both; one for the dependencies and one for the lockfile updates

meta: fix commit type on renovate dependency PRs

---

versioned_docs/version-6.x.x/core-concepts/assocs.md

Here in the [documentation](https://sequelize.org/docs/v6/core-concepts/assocs/#creating-updating-and-deleting), the link "[special methods/mixins](https://sequelize.org/docs/v6/core-concepts/assocs/#special-methods-mixins-added-to-instances)" is broken because of an additional dash between `methods` and `mixins` in the URL. Removing it fixes the problem.

Fix broken link on page

---

docs/other-topics/hooks.md
docs/other-topics/resources.md
docs/other-topics/typescript.mdx

As the title says
Sequelize-TypeScript won't work in v7, we'll update our documentation progressively as we add support for decorators natively

Replace sequelize-typescript with built-in decorators

---

docs/other-topics/upgrade.md

This PR documents an unintended breaking change that was introduced in v7 (discovered in https://github.com/sequelize/sequelize/issues/15463). The new behavior is IMO better so I propose to keep it.

Document `DataTypes.DATE` breaking change

---

docs/other-topics/hooks.md
versioned_docs/version-6.x.x/other-topics/hooks.md

As indicated in https://github.com/sequelize/sequelize/issues/2547, some of the information in the v6 documentation about hooks is false. 
The documentation says that the `hooks` option on association definitions is used to trigger hooks on association impacted by `ON DELETE CASCADE`.
I also added documentation about `individualHooks` to Sequelize 7, and added a section that details in which instances hooks do not trigger.

Remove false information about hooks

---

docs/other-topics/hooks.md
versioned_docs/version-6.x.x/other-topics/hooks.md

Sorry @WikiRik I jumped the gun too quickly on this one and my test had a flaw. Turned out the feature *does* exist but it uses the same option name as a different option (which is horrible, but I'll fix that in a separate PR)
This PR adds the documentation back, but adds a warning that using it is discouraged. We should look into providing trigger support instead of hacks like `individualHooks` and this option

Re-add documentation on "hooks" cascade hack

---

src/pages/releases.mdx

@ephys I will not touch the TypeScript page in our docs since I assume you will do that as part of #330 
See https://github.com/sequelize/sequelize/pull/15877

docs: update TypeScript version support

---

src/components/homepage-usage.tsx

This is a minor change to the usage example on the homepage.
The `Model` import isn't necessary, so it seemed better not to import it in the example, just to avoid any confusion.

Remove Model from usage example on homepage

---

docs/other-topics/hooks.md
versioned_docs/version-6.x.x/other-topics/hooks.md

Updated documentation for this issue: https://github.com/sequelize/sequelize/issues/15724

Document `afterPoolAcquire` & `beforePoolAcquire`

---

docs/index.mdx
docs/other-topics/upgrade.md
src/pages/releases.mdx

See https://github.com/sequelize/sequelize/pull/16058

fix: drop support for Node 14

---

versioned_docs/version-6.x.x/other-topics/resources.md

Added a link to `sequelize-browser` package on the Resources page. https://npmjs.com/package/sequelize-browser
Related PR: https://github.com/sequelize/sequelize/pull/16208
Related issue: https://github.com/sequelize/sequelize/issues/16207

Added a link to `sequelize-browser` package

---

docs/models/model-typing.mdx
docs/other-topics/utility-types.md

I noticed the links to the API docs in [Typing your model](https://sequelize.org/docs/v7/models/model-typing/) and [Utility TypeScript types](https://sequelize.org/docs/v7/other-topics/utility-types/) were broken, so I tried to fix them.
But there seems to be some sort of URL rewriting happening on the live website that doesn't happen in the local build. For example InferAttributes is at `http://localhost:3000/api/v7/types/_sequelize_core.index.InferAttributes.html` in the local build and at `https://sequelize.org/api/v7/types/_sequelize_core.index.inferattributes` on the live website.

Fix links to API v7 docs in model-typeing.md and utility-types.md

---

docs/models/data-types.mdx
docs/models/validations-and-constraints.md
docs/other-topics/upgrade.md
docs/querying/json.mdx

This PR:
- documents the change to how null is handled in JSON columns (#578)
- documents the MySQL schema change
- fixes an error in how model validators are used & documents static model validators
- documents a breaking change in through association casings

improve misc documentation issues

---

docs/other-topics/upgrade.md

This change was not made in v7

docs: removed incorrect breaking change

---

versioned_docs/version-6.x.x/core-concepts/model-querying-basics.md

`quoute` was misspelled, so I rightfully changed it to `quote`.

nit: fix typo

---

docs/models/defining-models.mdx
docs/other-topics/dialect-specific-things.md
src/pages/releases.mdx
versioned_docs/version-6.x.x/other-topics/dialect-specific-things.md

Updating the supported versions for MySQL for `@sequelize/core` version 7 as per sequelize/sequelize#17029

Drop MySQL 5.7 support in v7

---

docs/models/model-typing.mdx
versioned_docs/version-6.x.x/other-topics/typescript.md

The type `Optional` was renamed to `PartialBy` and is available in [@sequelize/utils](https://github.com/sequelize/sequelize/tree/main/packages/utils).
The documentation needed to be updated to reflect the change.
This fixes #716.

Update the type used in examples for optional creation attributes.

---

.github/CODEOWNERS
.github/FUNDING.yml
.github/workflows/autoupdate.yml

This PR implements the same workflow as https://github.com/sequelize/sequelize/pull/17271, but for the website repository
It also adds the codeowner file for automatic reviewer assignation, as well as updates the funding file

align workflows & metadata with main repo

---

docs/databases/mariadb.mdx

The type 'MariaDBDialect' doesn't exist and should be fixed to 'MariaDbDialect' like the code exports:
https://github.com/sequelize/sequelize/blob/b97a9b921dbec7c4a892c89ee03c7790ba48db8a/packages/mariadb/src/dialect.ts#L51

docs: fixing MariaDbDialect documentation

---

docs/querying/raw-queries.mdx
package.json
yarn.lock

This PR documents:
- changes to `sql.identifier`
- the new `sql.join` function
Related PR: https://github.com/sequelize/sequelize/pull/17744

document changes to sql functions
